server:
  host: "0.0.0.0"
  port: 18819
  workers: 2
  redis_host: "localhost"
  redis_port: 6379
  redis_db: 0

paths:
  model: "model.bin"
  rules_file: "default_rules.bin"
  medicine_file: "medicine.csv"
  name_file : "names.txt"
  extra_rules_file: ""
  city_file: "city.csv"
  
alg:
  person: "null"
  phone_number: "enc"
  location: "location"
  id_number: "enc"
  email: "null"
  bank_card: "null"